apiVersion: v1
kind: ConfigMap
metadata:
  name: rancher-fip-config
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "rancher-fip-cluster-manager.labels" . | nindent 4 }}
data:
{{- if .Values.clustermanager.RancherFipApiServerURL }}
  RancherFipApiServerURL: "{{ .Values.clustermanager.RancherFipApiServerURL }}"
{{- end }}
{{- if .Values.clustermanager.RancherFipLBControllerChartName }}
  RancherFipLBControllerChartName: "{{ .Values.clustermanager.RancherFipLBControllerChartName }}"
{{- end }}
{{- if .Values.clustermanager.RancherFipLBControllerChartRef }}
  RancherFipLBControllerChartRef: "{{ .Values.clustermanager.RancherFipLBControllerChartRef }}"
{{- end }}
{{- if .Values.clustermanager.RancherFipLBControllerChartVersion }}
  RancherFipLBControllerChartVersion: "{{ .Values.clustermanager.RancherFipLBControllerChartVersion }}"
{{- end }}
{{- if .Values.clustermanager.RancherFipLBControllerNamespace }}
  RancherFipLBControllerNamespace: "{{ .Values.clustermanager.RancherFipLBControllerNamespace }}"
{{- end }}
{{- if .Values.clustermanager.RancherFipLBControllerValues }}
  RancherFipLBControllerValues: |
    image:
      repository: "{{ .Values.clustermanager.RancherFipLBControllerValues.image.repository }}"
      tag: "{{ .Values.clustermanager.RancherFipLBControllerValues.image.tag }}"
{{- end }}
{{- if .Values.clustermanager.PureLBControllerChartName }}
  PureLBControllerChartName: "{{ .Values.clustermanager.PureLBControllerChartName }}"
{{- end }}
{{- if .Values.clustermanager.PureLBControllerChartRef }}
  PureLBControllerChartRef: "{{ .Values.clustermanager.PureLBControllerChartRef }}"
{{- end }}
{{- if .Values.clustermanager.PureLBControllerChartVersion }}
  PureLBControllerChartVersion: "{{ .Values.clustermanager.PureLBControllerChartVersion }}"
{{- end }}
{{- if .Values.clustermanager.PureLBControllerNamespace }}
  PureLBControllerNamespace: "{{ .Values.clustermanager.PureLBControllerNamespace }}"
{{- end }}
{{- if .Values.clustermanager.PureLBControllerValues }}
  PureLBControllerValues: |
    image:
      repository: "{{ .Values.clustermanager.PureLBControllerValues.image.repository }}"
      tag: "{{ .Values.clustermanager.PureLBControllerValues.image.tag }}"
    lbnodeagent:
      sendgarp: true
      nodeSelector:
        {{ .Values.clustermanager.PureLBControllerValues.lbnodeagent.nodeSelector | default "node-role.kubernetes.io/control-plane: 'true'" }}
      tolerations: {{ .Values.clustermanager.PureLBControllerValues.lbnodeagent.tolerations | default "[]" }}
    allocator:
      tolerations: {{ .Values.clustermanager.PureLBControllerValues.allocator.tolerations | default "[]" }}
{{- end }}
{{- if .Values.clustermanager.MetalLBControllerChartName }}
  MetalLBControllerChartName: "{{ .Values.clustermanager.MetalLBControllerChartName }}"
{{- end }}
{{- if .Values.clustermanager.MetalLBControllerChartRef }}
  MetalLBControllerChartRef: "{{ .Values.clustermanager.MetalLBControllerChartRef }}"
{{- end }}
{{- if .Values.clustermanager.MetalLBControllerChartVersion }}
  MetalLBControllerChartVersion: "{{ .Values.clustermanager.MetalLBControllerChartVersion }}"
{{- end }}
{{- if .Values.clustermanager.MetalLBControllerNamespace }}
  MetalLBControllerNamespace: "{{ .Values.clustermanager.MetalLBControllerNamespace }}"
{{- end }}
{{- if .Values.clustermanager.MetalLBControllerValues }}
  MetalLBControllerValues: |
    controller:
      image:
        repository: "{{ .Values.clustermanager.MetalLBControllerValues.controller.image.repository }}"
        tag: "{{ .Values.clustermanager.MetalLBControllerValues.controller.image.tag }}"
      nodeSelector:
        {{ .Values.clustermanager.MetalLBControllerValues.controller.nodeSelector | default "node-role.kubernetes.io/control-plane: 'true'" }}
      tolerations: {{ .Values.clustermanager.MetalLBControllerValues.controller.tolerations | default "[]" }}
    speaker:
      image:
        repository: "{{ .Values.clustermanager.MetalLBControllerValues.speaker.image.repository }}"
        tag: "{{ .Values.clustermanager.MetalLBControllerValues.speaker.image.tag }}"
      nodeSelector:
        {{ .Values.clustermanager.MetalLBControllerValues.speaker.nodeSelector | default "node-role.kubernetes.io/control-plane: 'true'" }}
      tolerations: {{ .Values.clustermanager.MetalLBControllerValues.speaker.tolerations | default "[]" }}
      frr:
        image:
          repository: "{{ .Values.clustermanager.MetalLBControllerValues.speaker.frr.image.repository }}"
          tag: "{{ .Values.clustermanager.MetalLBControllerValues.speaker.frr.image.tag }}"
{{- end }}
