apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rancher-fip-cluster-manager.fullname" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "rancher-fip-cluster-manager.labels" . | nindent 4 }}
spec:
  {{- if not .Values.clustermanager.autoscaling.enabled }}
  replicas: {{ .Values.clustermanager.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rancher-fip-cluster-manager.selectorLabels" . | nindent 6 }}
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.clustermanager.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rancher-fip-cluster-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.clustermanager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.clustermanager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.clustermanager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      {{- with .Values.clustermanager.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rancher-fip-cluster-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.clustermanager.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.clustermanager.securityContext | nindent 12 }}
          image: "{{ .Values.clustermanager.image.repository }}:{{ .Values.clustermanager.image.tag | default .Chart.AppVersion }}"
          args:
            - --leader-elect=true
            - --lease-lock-name={{ include "rancher-fip-cluster-manager.fullname" . }}-lock
            - --lease-lock-namespace={{ .Release.Namespace | default "kube-system" }}
            - --app-namespace={{ .Release.Namespace | default "kube-system" }}
          {{- with .Values.clustermanager.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.clustermanager.image.pullPolicy }}
          resources:
            {{- toYaml .Values.clustermanager.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
