{{- if .Values.clustermanager.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rancher-fip-cluster-manager.fullname" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "rancher-fip-cluster-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rancher-fip-cluster-manager.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "rancher-fip-cluster-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
{{- end }}
