{{- if .Values.clustermanager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rancher-fip-cluster-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "rancher-fip-cluster-manager.labels" . | nindent 4 }}
  {{- with .Values.clustermanager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
