apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-fip-manager-webhook.fullname" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "rancher-fip-manager-webhook.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "rancher-fip-manager-webhook.selectorLabels" . | nindent 8 }}
  ports:
    - name: webhook
      port: {{ .Values.webhook.service.webhookServicePort }}
      protocol: TCP
      targetPort: {{ .Values.webhook.service.webhookListenPort }}
  sessionAffinity: None
  type: ClusterIP
