{{- if .Values.manager.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rancher-fip-manager.fullname" . }}
  labels:
    {{- include "rancher-fip-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rancher-fip-manager.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "rancher-fip-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
{{- end }}
