apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-fip-manager.fullname" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "rancher-fip-manager.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "rancher-fip-manager.selectorLabels" . | nindent 8 }}
  ports:
    - name: manager
      port: {{ .Values.manager.service.httpServicePort }}
      protocol: TCP
      targetPort: {{ .Values.manager.service.httpListenPort }}
  sessionAffinity: None
  type: ClusterIP
