apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-fip-api-server.fullname" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "rancher-fip-api-server.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "rancher-fip-api-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.apiserver.service.apiPort | default 8080 }}
      protocol: TCP
      targetPort: {{ .Values.apiserver.service.apiPort | default 8080 }}
  sessionAffinity: None
  type: ClusterIP
{{- if .Values.apiserver.nodeport.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-fip-api-server.fullname" . }}-nodeport
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "rancher-fip-api-server.labels" . | nindent 4 }}
spec:
  ports:
    - name: api
      nodePort: {{ .Values.apiserver.nodeport.port | default 30443 }}
      port: {{ .Values.apiserver.service.apiPort | default 8080 }}
      protocol: TCP
      targetPort: {{ .Values.apiserver.service.apiPort | default 8080 }}
  selector:
    {{- include "rancher-fip-api-server.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: NodePort
{{- end }}
